[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11,<3.13"
dependencies = [
    "boto3>=1.40.61",
    "diskcache>=5.6.3",
    "mlflow>=3.5.1",
    "pyspark<=3.5.3",
    "python-dotenv>=1.1.1",
    "surprise>=0.1",
]

[project.scripts]
ml = "ml.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ml"]
package-dir = {"ml" = "src"}
