[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
requires-python = "<=3.12"
dependencies = [
    "mlflow>=3.5.1",
    "pyspark<=3.5.3",
    "python-dotenv>=1.1.1",
]

[project.scripts]
ml = "ml.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ml"]
package-dir = {"ml" = "src"}
