services:   
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow-server
    restart: unless-stopped
    command: >
      /bin/bash -c "
        pip install --no-cache-dir psycopg2-binary boto3 &&
        mlflow server \
          --backend-store-uri $$MLFLOW_BACKEND_STORE_URI \
          --default-artifact-root $$MLFLOW_DEFAULT_ARTIFACT_ROOT \
          --host $$MLFLOW_HOST \
          --port $$MLFLOW_PORT \
          --app-name mlflow-server
          "
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - AWS_ACCESS_KEY_ID=$${MLFLOW_S3_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=$${MLFLOW_S3_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=$${MLFLOW_S3_REGION}
      - MLFLOW_S3_ENDPOINT_URL=$${MLFLOW_S3_ENDPOINT_URL}
      - MLFLOW_SERVER_DISABLE_SECURITY_MIDDLEWARE=true