[project]
name = "database"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.30.0",
    "greenlet>=3.1.1",
    "sqlalchemy>=2.0.44",
]

[project.scripts]
database = "database.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["database"]
package-dir = {"database" = "."}
