[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
  "images",
  "text",
  "fastapi>=0.116.1",
  "uvicorn[standard]>=0.35.0",
  "colorlog>=6.9.0",
  "python-dotenv>=1.1.0"
]

[project.scripts]
api = "api.main:main"

[tool.uv.sources]
images = { workspace = true }
text = { workspace = true }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["api"]
package-dir = {"api" = "src"}
